### PR TITLE
Fixing Database file to work with txadmin

### PR DESCRIPTION
**Pull request by xOnlyFadi**
Added Jobmanager table because it didn't exist before which caused an error on console
image

### CODE REVIEW

**Comment by outsider31000** [comment]
image
thank you but you deleted the most important thing

**Comment by xOnlyFadi** [comment]
> image thank you but you deleted the most important thing

forgot to add in the message currently when txadmin is creating the server it's using a different database which is causing confusion for a lot people why their files are not working

**Comment by xOnlyFadi** [comment]
you can put a different sql file in txadmin reciepe to make it work without it creating 2 different databases

**Comment by outsider31000** [comment]
im not going to remove the creation of the the databse using a name thats in the server.cfg  to be set as path of database connection.

**Comment by xOnlyFadi** [comment]
then how would people that want to create their server in txadmin know the database name is different to make it work without any errors

**Comment by outsider31000** [comment]
What people need to use is this repo, not tx admin recepies.

**Comment by xOnlyFadi** [comment]
image

**Pull request closed without merging**
